using System;
using Oracle.ManagedDataAccess.Client;

namespace DBSetup
{
    class Program
    {
        static void Main(string[] args)
        {
            string connectionString = "User Id=system;Password=DB_BAOCAO2026;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))";
            
            using (OracleConnection conn = new OracleConnection(connectionString))
            {
                try
                {
                    conn.Open();
                    Console.WriteLine("Kết nối thành công!");

                    // 1. Tạo SCHEMA (User)
                    ExecuteSql(conn, "CREATE USER QUANTRI IDENTIFIED BY 123", "User QUANTRI");
                    ExecuteSql(conn, "GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO QUANTRI", "Grant QUANTRI");
                    ExecuteSql(conn, "CREATE USER BAOCAO IDENTIFIED BY 123", "User BAOCAO");
                    ExecuteSql(conn, "GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO BAOCAO", "Grant BAOCAO");

                    // 2. Tạo bảng QUANTRI.DM_DON_VI
                    string sqlDonVi = @"
                        CREATE TABLE QUANTRI.DM_DON_VI
                        (
                          ID_DV           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 50001 MAXVALUE 9999999999999999999999999999 MINVALUE 1611 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
                          MA_DV           NVARCHAR2(50),
                          KY_HIEU         NVARCHAR2(2000),
                          ID_ESB_QG       NVARCHAR2(50),
                          TEN_DV          NVARCHAR2(255),
                          ID_DV_CHA       NUMBER(10)                    DEFAULT ON NULL 0             NOT NULL,
                          STT             NUMBER(10)                    DEFAULT ON NULL 0             NOT NULL,
                          ESB             NUMBER(1)                     DEFAULT ON NULL 0             NOT NULL,
                          DISABLE         NUMBER(1)                     DEFAULT ON NULL 0             NOT NULL,
                          LOG_XULY        NVARCHAR2(2000),
                          DIA_CHI         NVARCHAR2(1000),
                          EMAIL           NVARCHAR2(255),
                          DINH_DANH       NVARCHAR2(255),
                          DIEN_THOAI      NVARCHAR2(50),
                          FAX             NVARCHAR2(50),
                          TEN_CON_DAU     NVARCHAR2(1000),
                          ANH_CON_DAU     BLOB                          DEFAULT ON NULL EMPTY_BLOB()  NOT NULL,
                          MA_NGACH        NVARCHAR2(50),
                          LOGO            BLOB                          DEFAULT ON NULL EMPTY_BLOB()  NOT NULL,
                          ANH_CON_DAU_DU  BLOB,
                          ANH_CON_DAU_CD  BLOB,
                          MA_DV_ESB       NVARCHAR2(50),
                          UBQLV           NVARCHAR2(200)
                        )";

                    ExecuteSql(conn, sqlDonVi, "QUANTRI.DM_DON_VI");

                    // 3. Tạo bảng BAOCAO.BC_VP_QD_296_BIEU_3
                    string sqlBaoCao = @"
                        CREATE TABLE BAOCAO.BC_VP_QD_296_BIEU_3 (
                            ID         NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            ID_DV      NUMBER,
                            COT_1      NUMBER,
                            COT_2      NUMBER,
                            COT_3      NUMBER,
                            COT_4      NUMBER,
                            COT_5      NUMBER,
                            COT_6      NUMBER,
                            COT_7      NUMBER,
                            COT_8      NUMBER,
                            COT_9      NUMBER,
                            COT_10     NUMBER,
                            COT_11     NUMBER,
                            COT_12     NUMBER,
                            COT_13     NUMBER,
                            COT_14     NUMBER,
                            DISABLE    NUMBER(1) DEFAULT 0,
                            NGAY_TAO   DATE DEFAULT SYSDATE
                        )";

                    ExecuteSql(conn, sqlBaoCao, "BAOCAO.BC_VP_QD_296_BIEU_3");

                    // 4. Chèn dữ liệu mẫu
                    string sqlInsertDonVi = "INSERT INTO QUANTRI.DM_DON_VI (MA_DV, TEN_DV) VALUES ('DV01', 'Đơn vị Kiểm tra A')";
                    ExecuteSql(conn, sqlInsertDonVi, "Dữ liệu mẫu Đơn vị");

                    string sqlInsertBaoCao = "INSERT INTO BAOCAO.BC_VP_QD_296_BIEU_3 (ID_DV, COT_1, COT_2, COT_13, COT_14) VALUES (50001, 10, 5, 8, 10)";
                    ExecuteSql(conn, sqlInsertBaoCao, "Dữ liệu mẫu Báo cáo");

                    Console.WriteLine("Hoàn tất tạo Database!");
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Lỗi: " + ex.Message);
                }
            }
        }

        static void ExecuteSql(OracleConnection conn, string sql, string tableName)
        {
            try
            {
                using (OracleCommand cmd = new OracleCommand(sql, conn))
                {
                    cmd.ExecuteNonQuery();
                    Console.WriteLine("Đã tạo/chèn: " + tableName);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Bỏ qua hoặc Lỗi " + tableName + ": " + ex.Message);
            }
        }
    }
}
